"""
Mapeamentos de codigos DHS para rotulos legiveis em portugues.
Baseado nos dicionarios de dados do DHS Program (Demographic and Health Surveys).
"""

# ==============================================================================
# NOMES DE COLUNAS (por tabela)
# ==============================================================================

COLUMN_LABELS = {
    # Colunas comuns a varias tabelas
    "__common__": {
        "pais_codigo": "Codigo do Pais",
        "pais_nome": "Pais",
        "levantamento_id": "ID do Levantamento",
        "fase": "Fase DHS",
        "arquivo_origem": "Arquivo de Origem",
        "linha_origem": "Linha de Origem",
        "id_domicilio": "ID do Domicilio",
        "id_morador": "ID do Morador",
        "id_parceiro": "ID do Parceiro",
    },
    "Mulher": {
        "caseid": "ID do Caso",
        "v001": "N do Cluster",
        "v002": "N do Domicilio",
        "v003": "N da Linha (Mulher)",
        "v005": "Peso Amostral",
        "v006": "Mes da Entrevista",
        "v007": "Ano da Entrevista",
        "v008": "Data da Entrevista (CMC)",
        "v008a": "Data da Entrevista (dias desde jan/1900)",
        "v012": "Idade Atual (anos)",
        "v013": "Grupo Etario",
        "v024": "Regiao/Estado",
        "v025": "Area",
        "v106": "Nivel de Educacao",
        "v190": "Indice de Riqueza",
        "v201": "Total de Filhos Nascidos Vivos",
        "v212": "Idade ao Primeiro Nascimento",
        "v301": "Conhecimento de Anticoncepcional",
        "v302": "Uso Atual de Anticoncepcional",
        "v302a": "Uso Anticoncepcional (por tipo)",
        "v304_01": "Conhece: Pilula",
        "v304_02": "Conhece: DIU",
        "v304_03": "Conhece: Injecao",
        "v304_04": "Conhece: Diafragma",
        "v304_05": "Conhece: Preservativo Masculino",
        "v304_06": "Conhece: Esterilizacao Feminina",
        "v304_07": "Conhece: Esterilizacao Masculina",
        "v304_08": "Conhece: Abstinencia Periodica",
        "v304_09": "Conhece: Coito Interrompido",
        "v304_10": "Conhece: Amenorreia Lactacional",
        "v304_11": "Conhece: Preservativo Feminino",
        "v304_12": "Conhece: Implante",
        "v304_13": "Conhece: Outro",
        "v304_14": "Conhece: Contraceptivo de Emergencia",
        "v304_15": "Conhece: Anel Vaginal",
        "v304_16": "Conhece: Espermicida",
        "v304_17": "Conhece: Adesivo Anticoncepcional",
        "v304_18": "Conhece: Colar do Ciclo",
        "v304_19": "Conhece: Implante (outro)",
        "v304_20": "Conhece: Outro Metodo",
        "v305_01": "Usou: Pilula",
        "v305_02": "Usou: DIU",
        "v305_03": "Usou: Injecao",
        "v305_04": "Usou: Diafragma",
        "v305_05": "Usou: Preservativo Masculino",
        "v305_06": "Usou: Esterilizacao Feminina",
        "v305_07": "Usou: Esterilizacao Masculina",
        "v305_08": "Usou: Abstinencia Periodica",
        "v305_09": "Usou: Coito Interrompido",
        "v305_10": "Usou: Amenorreia Lactacional",
        "v305_11": "Usou: Preservativo Feminino",
        "v305_12": "Usou: Implante",
        "v305_13": "Usou: Outro",
        "v305_14": "Usou: Contraceptivo de Emergencia",
        "v305_15": "Usou: Anel Vaginal",
        "v305_16": "Usou: Espermicida",
        "v305_17": "Usou: Adesivo Anticoncepcional",
        "v305_18": "Usou: Colar do Ciclo",
        "v305_19": "Usou: Implante (outro)",
        "v305_20": "Usou: Outro Metodo",
        "v307_01": "Usa Atualmente: Pilula",
        "v307_02": "Usa Atualmente: DIU",
        "v307_03": "Usa Atualmente: Injecao",
        "v307_04": "Usa Atualmente: Diafragma",
        "v307_05": "Usa Atualmente: Preservativo Masculino",
        "v307_06": "Usa Atualmente: Esterilizacao Feminina",
        "v307_07": "Usa Atualmente: Esterilizacao Masculina",
        "v307_08": "Usa Atualmente: Abstinencia Periodica",
        "v307_09": "Usa Atualmente: Coito Interrompido",
        "v307_10": "Usa Atualmente: Amenorreia Lactacional",
        "v307_11": "Usa Atualmente: Preservativo Feminino",
        "v307_12": "Usa Atualmente: Implante",
        "v307_13": "Usa Atualmente: Outro",
        "v307_14": "Usa Atualmente: Contraceptivo de Emergencia",
        "v307_15": "Usa Atualmente: Anel Vaginal",
        "v307_16": "Usa Atualmente: Espermicida",
        "v307_17": "Usa Atualmente: Adesivo Anticoncepcional",
        "v307_18": "Usa Atualmente: Colar do Ciclo",
        "v307_19": "Usa Atualmente: Implante (outro)",
        "v307_20": "Usa Atualmente: Outro Metodo",
        "v312": "Metodo Anticoncepcional Atual",
        "v313": "Tipo de Metodo Anticoncepcional",
        "m3a_1": "Assistencia Pre-Natal: Medico (ult. filho)",
        "m3b_1": "Assistencia Pre-Natal: Enfermeira/Parteira (ult. filho)",
        "m4_1": "Aleitamento Materno - meses (ult. filho)",
        "m5_1": "Aleitamento Pos-Parto - meses (ult. filho)",
        "m13_1": "Consultas Pre-Natal (ult. filho)",
        "m14_1": "N de Consultas Pre-Natal (ult. filho)",
        "m15_1": "Local do Parto (ult. filho)",
        "m17_1": "Parto Cesarea (ult. filho)",
        "m18_1": "Assistencia no Parto (ult. filho)",
        "m19_1": "Peso ao Nascer gramas (ult. filho)",
        "m34_1": "Cuidados Pos-Parto nas 2h (ult. filho)",
        "m35_1": "Vacina TT (ult. filho)",
        "m36_1": "Meses de Amamentacao (ult. filho)",
        "m38_1": "Diarreia nas 2 semanas (ult. filho)",
        "m39_1": "Febre nas 2 semanas (ult. filho)",
        "v445": "IMC (Indice de Massa Corporal)",
        "v453": "Anemia (nivel de hemoglobina)",
        "v457": "Nivel de Anemia",
    },
    "Nascimento": {
        "caseid": "ID do Caso",
        "bidx": "Indice do Nascimento",
        "v001": "N do Cluster",
        "v002": "N do Domicilio",
        "v003": "N da Linha (Mulher)",
        "v005": "Peso Amostral",
        "bord": "Ordem de Nascimento",
        "b0": "Gemelar (0=nao; 1=1o; 2=2o...)",
        "b1": "Mes do Nascimento",
        "b2": "Ano do Nascimento",
        "b3": "Data de Nascimento (CMC)",
        "b4": "Sexo do Filho",
        "b5": "Filho Esta Vivo",
        "b6": "Idade na Morte (meses imprecisos)",
        "b7": "Idade na Morte (meses)",
        "b8": "Idade Atual do Filho (anos)",
        "b9": "Filho Mora com a Mae",
        "b10": "Completude da Data de Nascimento",
        "b11": "Intervalo desde Nascimento Anterior (meses)",
        "b12": "Intervalo ate Proximo Nascimento (meses)",
        "b13": "Ainda Amamentando",
        "b15": "Atencao ao Nascimento",
        "b16": "Linha do Filho no Quest. de Domicilio",
        "b17": "Parto Cesarea",
        "b18": "Tamanho ao Nascer (informado pela mae)",
        "b19": "Meses de Amamentacao Atual",
        "b20": "Duracao da Gestacao (semanas)",
        "b21": "Duracao da Gestacao (meses)",
        "m3a": "Cuidado Pre-Natal: Medico",
        "m3b": "Cuidado Pre-Natal: Enfermeira/Parteira",
        "m4": "Duracao do Aleitamento Materno (meses)",
        "m5": "Duracao do Aleitamento Pos-Parto (meses)",
        "m6": "Duracao de Abstinencia Pos-Parto (meses)",
        "m7": "Duracao de Amenorreia Pos-Parto (meses)",
        "m13": "Numero de Consultas Pre-Natais",
        "m14": "Numero de Consultas Pre-Natais (recodificado)",
        "m15": "Local do Parto",
        "m17": "Parto Cesarea",
        "m18": "Profissional que Assistiu o Parto",
        "m19": "Peso ao Nascer (gramas)",
        "m34": "Cuidados Pos-Parto nas 2h Seguintes",
        "m35": "Vacina Antitetanica durante Gravidez",
        "m36": "Meses de Amamentacao",
        "m38": "Diarreia nas 2 Semanas Anteriores",
        "m39a": "Febre nas 2 Semanas Anteriores",
        "h1": "Cartao de Vacinacao Visto",
        "h2": "Vacina BCG",
        "h3": "Vacina DTP 1",
        "h4": "Vacina Polio 1",
        "h5": "Vacina DTP 2",
        "h6": "Vacina Polio 2",
        "h7": "Vacina DTP 3",
        "h8": "Vacina Polio 3",
        "h9": "Vacina Sarampo/Rubeola",
    },
    "Domicilio": {
        "hhid": "ID do Domicilio",
        "hv001": "N do Cluster",
        "hv002": "N do Domicilio",
        "hv003": "Linha do Responsavel",
        "hv005": "Peso Amostral",
        "hv009": "N de Membros do Domicilio",
        "hv012": "Homens no Domicilio",
        "hv013": "Mulheres no Domicilio",
        "hv024": "Regiao/Estado",
        "hv025": "Area",
        "hv201": "Fonte de Agua para Beber",
        "hv205": "Tipo de Instalacao Sanitaria",
        "hv206": "Tem Eletricidade",
        "hv207": "Tem Radio",
        "hv208": "Tem Televisao",
        "hv209": "Tem Geladeira",
        "hv210": "Tem Bicicleta",
        "hv211": "Tem Motocicleta/Scooter",
        "hv212": "Tem Carro/Caminhao",
        "hv213": "Material do Piso",
        "hv214": "Material das Paredes Externas",
        "hv215": "Material do Telhado",
        "hv216": "N de Quartos para Dormir",
        "hv217": "Estrutura do Domicilio",
        "hv218": "Linha da Mulher Elegivel Mais Velha",
        "hv219": "Sexo do Chefe do Domicilio",
        "hv220": "Idade do Chefe do Domicilio",
        "hv221": "Tem Telefone Fixo",
        "hv222": "Linha da Mulher Elegivel Mais Nova",
        "hv223": "Combustivel para Cozinhar",
        "hv225": "Domicilio Compartilha Banheiro",
        "hv226": "Combustivel para Iluminacao",
        "hv227": "Tem Mosquiteiro",
        "hv228": "Criancas <5 anos Dormem sob Mosquiteiro",
        "hv230a": "Lavagem das Maos: Local Observado",
        "hv232": "Tem Sabao no Local de Lavagem",
        "hv234": "Sal Iodado no Domicilio",
        "hv235": "Local de Lavagem das Maos",
        "hv236a": "Tem Agua no Local de Lavagem",
        "hv237": "Membro Assinou Beneficio Social",
        "hv240": "Tem Celular",
        "hv270": "Indice de Riqueza",
        "hv271": "Pontuacao do Indice de Riqueza (fator)",
    },
    "Morador": {
        "hhid": "ID do Domicilio",
        "hvidx": "Indice do Membro",
        "hv001": "N do Cluster",
        "hv002": "N do Domicilio",
        "hv003": "Linha do Responsavel",
        "hv004": "N de Unidade Primaria de Amostragem",
        "hv005": "Peso Amostral",
        "hv009": "N de Membros do Domicilio",
        "hv012": "Homens no Domicilio",
        "hv013": "Mulheres no Domicilio",
        "hv024": "Regiao/Estado",
        "hv025": "Area",
        "hv101": "Relacao com Chefe do Domicilio",
        "hv102": "Residente Usual",
        "hv103": "Dormiu no Domicilio Ontem",
        "hv104": "Sexo",
        "hv105": "Idade (anos)",
        "hv106": "Nivel de Educacao",
        "hv107": "Ultimo Ano de Escolaridade",
        "hv108": "Anos de Escolaridade",
        "hv109": "Nivel de Educacao (cat.)",
        "hv110": "E Chefe do Domicilio",
        "hv111": "Mae Mora no Domicilio",
        "hv112": "Linha da Mae no Questionario",
        "hv113": "Pai Mora no Domicilio",
        "hv114": "Linha do Pai no Questionario",
        "hv115": "Estado Civil",
        "hv116": "Casou nos Ultimos 12 Meses",
        "hv117": "Elegivel para Entrevista (mulher)",
        "hv118": "Elegivel para Entrevista (homem)",
        "hv120": "Elegivel para Medicao (crianca <5 anos)",
        "hv121": "Frequenta Escola",
        "hv122": "Nivel de Escolaridade Atual",
        "hv123": "Serie Atual",
        "hv124": "Educacao em Area Especial",
        "hv125": "Completou Alguma Serie",
        "hv126": "Educacao Especial",
        "hv127": "Altura cm (fator x10)",
        "hv128": "Peso kg (fator x10)",
        "hv129": "Estado Nutricional",
    },
    "Parceiro": {
        "mcaseid": "ID do Caso",
        "mv001": "N do Cluster",
        "mv002": "N do Domicilio",
        "mv003": "N da Linha (Homem)",
        "mv005": "Peso Amostral",
        "mv012": "Idade Atual (anos)",
        "mv024": "Regiao/Estado",
        "mv025": "Area",
        "mv106": "Nivel de Educacao",
        "mv190": "Indice de Riqueza",
        "mv201": "Total de Filhos Tidos",
        "mv212": "Idade ao Primeiro Filho",
    },
    "Crianca": {
        "caseid": "ID do Caso",
        "bidx": "Indice do Nascimento",
        "v001": "N do Cluster",
        "v002": "N do Domicilio",
        "v003": "N da Linha",
        "v005": "Peso Amostral",
        "bidxp": "Indice no Quest. de Domicilio",
        "b0": "Gemelar",
        "b1": "Mes do Nascimento",
        "b2": "Ano do Nascimento",
        "b3": "Data de Nascimento (CMC)",
        "b4": "Sexo",
        "b5": "Crianca Esta Viva",
        "b6": "Idade na Morte (meses imprecisos)",
        "b7": "Idade na Morte (meses)",
        "b8": "Idade Atual (anos)",
        "b9": "Mora com a Mae",
        "b10": "Completude da Data de Nascimento",
        "b11": "Intervalo desde Nascimento Anterior",
        "b12": "Intervalo ate Proximo Nascimento",
        "m4": "Duracao do Aleitamento (meses)",
        "m5": "Aleitamento Pos-Parto (meses)",
        "m6": "Abstinencia Pos-Parto (meses)",
        "m7": "Amenorreia Pos-Parto (meses)",
        "m13": "N de Consultas Pre-Natais",
        "m14": "N de Consultas Pre-Natais (recodificado)",
        "m15": "Local do Parto",
        "m17": "Parto Cesarea",
        "m18": "Profissional que Assistiu o Parto",
        "m19": "Peso ao Nascer (gramas)",
        "m34": "Cuidados Pos-Parto nas 2h",
        "m35": "Vacina TT durante Gravidez",
        "m36": "Meses de Amamentacao",
        "m38": "Diarreia nas 2 Semanas",
        "m39a": "Febre nas 2 Semanas",
        "h1": "Cartao de Vacinacao Visto",
        "h2": "BCG", "h3": "DTP 1", "h4": "Polio 1",
        "h5": "DTP 2", "h6": "Polio 2", "h7": "DTP 3",
        "h8": "Polio 3", "h9": "Sarampo/Rubeola",
    },
    "Indice_Riqueza": {
        "whhid": "ID do Domicilio",
        "wlthindf": "Pontuacao do Indice de Riqueza (fator continuo)",
        "wlthind5": "Indice de Riqueza (quintil)",
    },
    "Levantamento": {
        "levantamento_id": "ID do Levantamento",
        "pais_codigo": "Codigo do Pais",
        "fase": "Fase DHS",
    },
    "Pais": {
        "pais_codigo": "Codigo do Pais (ISO 2)",
        "nome_pais": "Nome do Pais",
    },
    "Manifesto_Selecao": {
        "pais_codigo": "Codigo do Pais",
        "pais_nome": "Pais",
        "fase": "Fase DHS",
        "recode": "Tipo de Recode",
        "arquivo_origem": "Arquivo Stata de Origem",
        "caminho_origem": "Caminho Original do Arquivo",
        "linhas": "N de Linhas",
        "colunas_selecionadas": "N de Colunas Selecionadas",
        "colunas": "Lista de Colunas",
    },
}

# ==============================================================================
# MAPEAMENTOS DE VALORES (codigo -> rotulo)
# ==============================================================================

VALUE_MAPS = {
    "v025":  {1: "Urbano", 2: "Rural"},
    "hv025": {1: "Urbano", 2: "Rural"},
    "mv025": {1: "Urbano", 2: "Rural"},
    "v106":  {0: "Sem educacao", 1: "Primario", 2: "Secundario", 3: "Superior", 8: "Nao aplicavel", 9: "Nao sei"},
    "hv106": {0: "Sem educacao", 1: "Primario", 2: "Secundario", 3: "Superior", 8: "Nao aplicavel", 9: "Nao sei"},
    "mv106": {0: "Sem educacao", 1: "Primario", 2: "Secundario", 3: "Superior", 8: "Nao aplicavel", 9: "Nao sei"},
    "hv122": {0: "Sem educacao", 1: "Primario", 2: "Secundario", 3: "Superior", 8: "Nao aplicavel", 9: "Nao sei"},
    "v190":  {1: "Mais pobre", 2: "Pobre", 3: "Medio", 4: "Rico", 5: "Mais rico"},
    "hv270": {1: "Mais pobre", 2: "Pobre", 3: "Medio", 4: "Rico", 5: "Mais rico"},
    "mv190": {1: "Mais pobre", 2: "Pobre", 3: "Medio", 4: "Rico", 5: "Mais rico"},
    "wlthind5": {1: "Mais pobre", 2: "Pobre", 3: "Medio", 4: "Rico", 5: "Mais rico"},
    "v013": {1:"15-19 anos",2:"20-24 anos",3:"25-29 anos",4:"30-34 anos",5:"35-39 anos",6:"40-44 anos",7:"45-49 anos",8:"50-54 anos",9:"55-59 anos",10:"60-64 anos"},
    "b4":  {1: "Masculino", 2: "Feminino"},
    "hv104": {1: "Masculino", 2: "Feminino"},
    "b5":  {0: "Nao", 1: "Sim"},
    "b9":  {0: "Com a mae", 1: "Com outra pessoa", 4: "Falecida"},
    "b13": {0: "Nao", 1: "Sim"},
    "b17": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m17": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m17_1": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m3a": {0: "Nao", 1: "Sim"},
    "m3b": {0: "Nao", 1: "Sim"},
    "m3a_1": {0: "Nao", 1: "Sim"},
    "m3b_1": {0: "Nao", 1: "Sim"},
    "m34": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m34_1": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m35": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m35_1": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m38": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m38_1": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m39a": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "m39_1": {0: "Nao", 1: "Sim", 9: "Nao sei"},
    "h1": {0: "Nao visto", 1: "Visto", 9: "Nao sei"},
    "h2": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 3: "Vacinado (cicatriz)", 8: "Nao aplicavel"},
    "h3": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 8: "Nao aplicavel"},
    "h4": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 8: "Nao aplicavel"},
    "h5": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 8: "Nao aplicavel"},
    "h6": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 8: "Nao aplicavel"},
    "h7": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 8: "Nao aplicavel"},
    "h8": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 8: "Nao aplicavel"},
    "h9": {0: "Nao", 1: "Vacinado (cartao)", 2: "Vacinado (relatado)", 8: "Nao aplicavel"},
    "m18": {1:"Medico",2:"Enfermeira/Parteira qualificada",3:"Parteira tradicional",4:"Parente/Amigo",5:"Outro",8:"Nao aplicavel",9:"Nao sei"},
    "m18_1": {1:"Medico",2:"Enfermeira/Parteira qualificada",3:"Parteira tradicional",4:"Parente/Amigo",5:"Outro",8:"Nao aplicavel",9:"Nao sei"},
    "m15": {11:"Domicilio proprio",12:"Casa de outra pessoa",13:"Outro domicilio",14:"Em transito",21:"Hospital publico",22:"Centro de saude publico",23:"Clinica publica",24:"Maternidade publica",25:"Posto de saude publico",26:"Unidade movel publica",27:"Outro setor publico",31:"Hospital privado",32:"Clinica privada",33:"Maternidade privada",34:"Consultorio medico privado",35:"ONG/Missao/Igreja",36:"Outro setor privado",39:"Outro setor privado (2)",41:"Hospital misto",42:"Clinica mista",43:"Centro de saude misto",44:"Outro misto",51:"Farmacia",52:"Outro (externo)",96:"Outro",99:"Nao sei"},
    "m15_1": {11:"Domicilio proprio",12:"Casa de outra pessoa",13:"Outro domicilio",21:"Hospital publico",22:"Centro de saude publico",23:"Clinica publica",24:"Maternidade publica",25:"Posto de saude publico",31:"Hospital privado",32:"Clinica privada",33:"Maternidade privada",34:"Consultorio medico privado",35:"ONG/Missao/Igreja",96:"Outro",99:"Nao sei"},
    "v312": {0:"Nao usa",1:"Pilula",2:"DIU",3:"Injecao",4:"Diafragma",5:"Preservativo masculino",6:"Esterilizacao feminina",7:"Esterilizacao masculina",8:"Abstinencia periodica",9:"Coito interrompido",10:"Amenorreia lactacional (LAM)",11:"Preservativo feminino",12:"Implante",13:"Outro metodo moderno",14:"Contraceptivo de emergencia",15:"Anel vaginal",16:"Adesivo anticoncepcional",17:"Espermicida",18:"Colar do ciclo",19:"Outro metodo tradicional"},
    "v313": {0:"Nenhum",1:"Metodo folclorico",2:"Metodo tradicional",3:"Metodo moderno"},
    "v301": {0:"Nenhum metodo conhecido",1:"Apenas metodos folcloricos",2:"Apenas metodos tradicionais",3:"Metodos modernos"},
    "v302": {0:"Nunca usou",1:"Usou antes, nao usa mais",2:"Usa atualmente",3:"Usa atualmente (2)"},
    "v302a": {0:"Nunca usou",1:"Usou antes",2:"Usa atualmente"},
    "hv101": {1:"Chefe do domicilio",2:"Conjuge/parceiro(a)",3:"Filho(a)",4:"Genro/Nora",5:"Neto(a)",6:"Pai/Mae",7:"Sogro(a)",8:"Irmao/Irma",9:"Co-esposa",10:"Outro parente",11:"Adotado/Tutelado",12:"Nao parente",13:"Funcionario domestico",14:"Outro",98:"Nao sei",99:"Sem resposta"},
    "hv102": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv103": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv115": {0:"Nunca casou/uniao",1:"Casado(a)",2:"Em uniao estavel",3:"Viuvo(a)",4:"Divorciado(a)/Separado(a)",5:"Separado(a)",9:"Nao sei"},
    "hv110": {0:"Nao",1:"Sim"},
    "hv117": {0:"Nao elegivel",1:"Elegivel"},
    "hv118": {0:"Nao elegivel",1:"Elegivel"},
    "hv120": {0:"Nao elegivel",1:"Elegivel"},
    "hv121": {0:"Nao frequenta",2:"Frequenta escola",9:"Nao sei"},
    "hv116": {0:"Nao",1:"Sim",2:"Sim (2)",9:"Nao sei"},
    "hv125": {0:"Nao",1:"Sim"},
    "hv206": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv207": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv208": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv209": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv210": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv211": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv212": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv221": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv240": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv227": {0:"Nao",1:"Sim",9:"Nao sei"},
    "hv213": {11:"Terra/Areia",12:"Esterco",13:"Madeira bruta",21:"Madeira polida/Parquet",22:"Vinil/Linoleo/Borracha",23:"Ceramica/Porcelana",24:"Cimento",31:"Tapete",32:"Outro material de qualidade",33:"Outro",34:"Pedra/Marmore/Granito",35:"Tijolo",36:"Outro material natural",96:"Outro",99:"Nao sei"},
    "hv214": {11:"Sem parede",12:"Bambu/Junco/Juta",13:"Madeira bruta/Tronco",14:"Pedra com barro",21:"Pedra com cal/Cimento",22:"Tijolo sem reboco",23:"Tijolo com reboco",24:"Blocos de cimento",25:"Madeira serrada",26:"Chapas de zinco",27:"Outro material duradouro",28:"Chapas de amianto",31:"Outros",32:"Adobe/Barro cozido",33:"Barro prensado",34:"Adobe+Cimento",35:"Taipa",36:"Madeira compensada",37:"Madeira serrada (2)",38:"Concreto pre-moldado",41:"Plastico",42:"Outro natural",43:"Outro temporario",44:"Outro permanente",96:"Outro",99:"Nao sei"},
    "hv215": {11:"Sem telhado",12:"Sape/Palha/Folha de palmeira",13:"Lama/Barro",21:"Chapa de metal/Zinco",22:"Madeira",23:"Telha",24:"Cimento/Concreto",25:"Chapas de amianto",26:"Outro material duradouro",31:"Telha ceramica",32:"Outro",33:"Plastico",34:"Madeira processada",35:"Chapa prensada",36:"Bambu",37:"Palha de coco",38:"Palha de arroz",39:"Outro natural",96:"Outro",99:"Nao sei"},
    "hv201": {11:"Agua encanada no domicilio",12:"Agua encanada no lote/quintal",13:"Torneira publica",14:"Agua encanada em vizinho",15:"Torneira publica (outro)",21:"Poco tubular/furo",22:"Poco escavado coberto",23:"Poco escavado nao coberto",31:"Nascente protegida",32:"Nascente nao protegida",33:"Agua coletada da chuva",41:"Caminhao-pipa",42:"Agua engarrafada",43:"Carroca com tonel",51:"Rio/Lago/Riacho",61:"Agua de superficie",62:"Lagoa/Represa/Canal",63:"Valeta de irrigacao",71:"Agua fornecida por vizinho",72:"Tanque/Cisterna/Barril",73:"Outra agua superficial",82:"Poco sem protecao (2)",92:"Outro",96:"Outro",99:"Nao sei"},
    "hv205": {11:"Privada com descarga (encanamento)",12:"Privada com descarga (fossa septica)",13:"Privada com descarga (local nao especificado)",14:"Privada com descarga (vala)",15:"Privada com descarga (rio/mar)",16:"Privada com descarga (outro)",21:"Latrina melhorada ventilada privada",22:"Latrina com laje privada",23:"Latrina sem laje/buraco no chao privada",24:"Latrina aberta privada",31:"Latrina melhorada ventilada compartilhada",41:"Vaso sanitario suspenso",42:"Balde/bacia",43:"Campo aberto/natureza",44:"Sem instalacao",51:"Outra instalacao compartilhada",52:"Latrina com laje compartilhada",53:"Latrina sem laje compartilhada",54:"Outro compartilhado",96:"Outro",99:"Nao sei"},
    "recode": {"IR":"Mulher (Individual Recode)","BR":"Nascimento (Birth Recode)","HR":"Domicilio (Household Recode)","PR":"Morador (Person Recode)","MR":"Homem/Parceiro (Man Recode)","KR":"Crianca (Child Recode)","WI":"Indice de Riqueza (Wealth Index)","SQ":"Servico Comunitario (Service Quality)"},
    "b10": {0:"Mes e ano exatos",1:"Mes completo, ano aproximado",2:"Mes aproximado, ano completo",3:"Mes e ano aproximados",4:"Baseado em declaracao da mae",5:"Estimado pelo entrevistador",6:"Incompleto (so ano)",7:"Estimado a partir de outros nascimentos",8:"Estimado a partir da idade"},
}


def get_column_label(table: str, column: str) -> str:
    table_labels = COLUMN_LABELS.get(table, {})
    if column in table_labels:
        return table_labels[column]
    common = COLUMN_LABELS.get("__common__", {})
    if column in common:
        return common[column]
    return column


def get_value_label(column: str, value):
    if value is None:
        return None
    col_map = VALUE_MAPS.get(column)
    if col_map and value in col_map:
        return col_map[value]
    return value


def get_all_column_labels(table: str, columns: list) -> dict:
    return {col: get_column_label(table, col) for col in columns}


def get_coded_columns() -> set:
    return set(VALUE_MAPS.keys())
